services:
  front:
    container_name: dev-vendiq2-webui
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: yarn dev --host
    volumes:
      - ./webui:/app

  pricer:
    container_name: dev-vendiq2-pricer
    build:
      context: ./pricer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    command: air
    volumes:
      - ./pricer:/app
    environment:
      - APP_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
    secrets:
      - SPAPI_REFRESH_TOKEN
      - LWA_CLIENT_ID
      - LWA_CLIENT_SECRET
 
  rabbitmq:
    container_name: dev-vendiq2-rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

secrets:
  SPAPI_REFRESH_TOKEN:
    file: ./secrets/spapi_refresh_token.txt
  LWA_CLIENT_ID:
    file: ./secrets/lwa_client_id.txt
  LWA_CLIENT_SECRET:
    file: ./secrets/lwa_client_secret.txt
