services:
  front:
    container_name: dev-vendiq2-webui
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: yarn dev --host
    volumes:
      - ./webui:/app

  api:
    container_name: dev-vendiq2-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: air
    volumes:
      - ./api:/app
    environment:
      - APP_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}

  pricer:
    container_name: dev-vendiq2-pricer
    build:
      context: ./pricer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    command: air
    volumes:
      - ./pricer:/app
    environment:
      - APP_ENV=development
    secrets:
      - SPAPI_REFRESH_TOKEN
      - LWA_CLIENT_ID
      - LWA_CLIENT_SECRET

secrets:
  SPAPI_REFRESH_TOKEN:
    file: ./secrets/spapi_refresh_token.txt
  LWA_CLIENT_ID:
    file: ./secrets/lwa_client_id.txt
  LWA_CLIENT_SECRET:
    file: ./secrets/lwa_client_secret.txt
