services:
  front:
    container_name: dev-vendiq2-webui
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: yarn dev --host
    volumes:
      - ./webui:/app

  api:
    container_name: dev-vendiq2-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: air
    volumes:
      - ./api:/app
    environment:
      - APP_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
